### ISSUE TITLE
calibre 5.2 master pull from 10/20/2020 B&N epub not decripting

### ISSUE THREAD

**Issue by gbm1961** [apprenticeharper/DeDRM_tools#1332]
When using calibre 5.2 and the tools version 7.0.0 downloading on 10/20/2020 made using make_release.py  not working with my B&N key that works with calibre 4.23 tools version  6.8.0. 

Test conditions Linux Mint 20--wine and nook study not installed,--using my B&N key that has not change in years--nook books downloaded to my android phone sd card then to calibre.

Works with Kindle and ADE YAH.

Test with calibre 5.2

DeDRM v7.0.0: Trying to decrypt 2940016394442_epub.v8.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: “2940016394442_epub.v8.epub” is a secure Barnes & Noble ePub
DeDRM v7.0.0: Trying Encryption key bnepubkey
DeDRM v7.0.0: Exception when trying to decrypt after 0.9 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 229, in ePubDecrypt
    result = ignobleepub.decryptBook(userkey, inf.name, of.name)
  File "calibre_plugins.dedrm.ignobleepub", line 244, in decryptBook
    key = keyb64.decode('base64')[:16]
AttributeError: 'str' object has no attribute 'decode'
DeDRM v7.0.0: Failed to decrypt with key bnepubkey after 0.9 seconds
DeDRM v7.0.0: Looking for new NOOK Study Keys after 0.9 seconds
DeDRM v7.0.0: Running ignoblekey.py under Wine
DeDRM v7.0.0: Command line: 'wine python.exe "/media/nobody/test/cp/CalibreConfig/plugins/DeDRM/libraryfiles/ignoblekey.py" "/media/nobody/test/cp/CalibreConfig/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v7.0.0: Found and decrypted 0 key files
DeDRM v7.0.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 306, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Test with calibre 4.23

Starting up Calibre from portable directory "/media/nobody/test/cp4"
Using library at /media/nobody/test/cp4/CalibreLibrary
DeDRM v6.8.0: Trying to decrypt 9780425286128_epub.v2.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “9780425286128_epub.v2.epub” is a secure Barnes & Noble ePub
DeDRM v6.8.0: Trying Encryption key bnepubkey
DeDRM v6.8.0: Finished after 2.7 seconds

Thanks bernie

**Comment by l-l-l-l-l-l** [comment]
AFAIK v7.0.0 is still under work.

**Comment by ElleKayEm** [comment]
Yeah, this definitely looks like a case of DeDRM 7 not being ready in this area.  B&N stuff might be tough as there is less interest or ability to check on these.  If you don't already have your key, you have to do a fair amount of work to get it now.

**Comment by gbm1961** [comment]
The commit:
 Python 3 fixes for Barnes&Noble ableeker 1 parent dbc5c2b commit f9d9b6016fb7bb1a577804cd9f35d6690eab98e4
Fixes this problem on my Linux Mint P.C. using 7.0

DeDRM v7.0.0: Trying to decrypt 9780425286128_epub.v2.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: “9780425286128_epub.v2.epub” is a secure Barnes & Noble ePub
DeDRM v7.0.0: Trying Encryption key bnepubkey
DeDRM v7.0.0: Finished after 0.6 seconds
Added Bendigo Shafter (Louis L'Amour's Lost Treasures) to db in: 0.1
Added 1 books in 1.1 seconds
