### ISSUE TITLE
ADE PDF Decryption doesn't work on 7.0.0b3

### ISSUE THREAD

**Issue by maforget** [apprenticeharper/DeDRM_tools#1393]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>DeDRM 7.0.0b3 ADE PDF Decryption</summary>

```log
DeDRM v7.0.0: Trying to decrypt Les Tuniques Bleues - tome 63 - La bataille du Cratère.pdf
DeDRM v7.0.0: Les Tuniques Bleues - tome 63 - La bataille du Cratère.pdf is a PDF ebook
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xba\xc0\xe8`\xa9\x92Ct+\xb7\x18L\x196\xa6_{\x9d\x87-\xf1\x03V=+y\x13\x13\xbb\xccTq', b'C:\\Users\\USERNAME\\Documents\\My Digital Editions\\Les Tuniques Bleues - tome 63 - La bataille du Crat\xc3\xa8re.pdf']
Added La bataille du Cratère to db in: 0.3
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
  File "calibre_plugins.dedrm.__init__", line 424, in PDFDecrypt
AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 343, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1Added 1 books in 1.2 seconds
```
</details>

**Comment by apprenticeharper** [comment]
Thanks for the report. It looks like more work is needed on the code that uses ineptpdf.py
